r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root :to => 'home#index'
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :sessions, :artists, :albums, :genres, :songs
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#  album_id   :integer
#

class Song < ActiveRecord::Base
  attr_accessible :filename, :image, :name, :genre_ids

  belongs_to :album
  belongs_to :artist

  has_and_belongs_to_many :mixtapes
  has_and_belongs_to_many :genres
end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  layout 'homepage'

  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to(songs_path)
    else
      render :new
    end
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
    render :new
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to(songs_path)
    else
      render :new
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def index
    @songs = Song.order(:name)
  end
end

r2013-02-18-tunr/app/helpers/songs_helper.rb
module SongsHelper
end

r2013-02-18-tunr/app/views/songs/edit.html.haml
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

r2013-02-18-tunr/app/views/songs/index.html.haml
%p.newlink= link_to('New Artist', new_artist_path, :class => 'button radius') if is_admin
%table
  - @artists.each do |artist|
    %tr{:class => cycle('row0', 'row1')}
      %td= link_to(artist.name, artist)
      %td= link_to('Edit', edit_artist_path(artist), :class => 'button radius tiny') if is_admin

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .five.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      <br>
      %h3 Add genres to a song
      - Genre.all.each do |genre|
        %span= genre.name
        = check_box_tag 'song[genre_ids][]', genre.id, genre.in?(@song.genres.to_a)
      <br>
      = f.submit nil, :class => 'button radius'
  .seven.columns

r2013-02-18-tunr/app/views/songs/show.html.haml
%table
  %th=@song.name
  %p=@song.album.name

r2013-02-18-tunr/app/views/songs/update.html.erb
<h1>Songs#update</h1>
<p>Find me in app/views/songs/update.html.erb</p>